apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexric.fullname" . }}
  labels:
    {{- include "flexric.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}  
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
  {{- end }}
  selector:
    {{- include "flexric.selectorLabels" . | nindent 4 }}
