name: FlexRIC CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup and install Swig
        uses: mmomtchev/setup-swig@v1
        with:
          version: v4.2.1

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: | 
              libsctp-dev
              cmake-curses-gui
              libpcre2-dev
              python3-dev
              ccache
              build-essential
              curl
              gcc-13
              g++-13
              libtool
              m4
              bison
              flex
              gdb
              mold
              ninja-build
              automake
          version: 1.0
      
      - name: Build FlexRIC
        run: |
          cd submodules/flexric
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_FLAGS_RELEASE="-O3" \
                -DCMAKE_CXX_FLAGS_RELEASE="-O3" \
                -DCMAKE_C_COMPILER=gcc-13 \
                -DCMAKE_CXX_COMPILER=g++-13 \
                -DE2AP_VERSION=E2AP_V3 \
                -DKPM_VERSION=KPM_V3_00 ..
          ninja

      - name: Copy binaries
        run: bash scripts/cpRicFiles.sh

      - name: Configure Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            muriloavlis/flexric
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "docker/Dockerfile.flexric.ubuntu"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}